export const ActionTypes = {
    SET_PRODUCT : "SET_PRODUCT",
    SET_SELECTED_PRODUCTS : "SET_SELECTED_PRODUCTS",
    SET_REMOVED_PRODUCTS : "SET_REMOVED_PRODUCTS",
    ADD_TO_CART : "ADD_TO_CART",
    SET_PRODUCT_CATEGORIES : "SET_PRODUCT_CATEGORIES"
}