export const ActionTypes = {
    SET_PRODUCT : "SET_PRODUCT",
    SET_SELECTED_PRODUCTS : "SET_SELECTED_PRODUCTS",
    SET_REMOVED_PRODUCTS : "SET_REMOVED_PRODUCTS",
    ADD_TO_CART : "ADD_TO_CART",
    SET_PRODUCT_CATEGORIES : "SET_PRODUCT_CATEGORIES",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    REMOVE_ALL_CART_PRODUCT : "REMOVE_ALL_CART_PRODUCT",
    ADD_USER_ADDRESS : "ADD_USER_ADDRESS",
    SELECTED_CHECKOUT_PRODUCT : "SELECTED_CHECKOUT_PRODUCT", 
}